### PR TITLE
VULCAN-1553 Install setuptools_rust as a requirement before ansible requirements.txt

### PR DESCRIPTION
**Pull request by sjagoe**
setuptools_rust is required for installing cryptography >= 3.4

### CODE REVIEW

**Comment by sjagoe** [comment]
I guess we could pin cryptography in smartly-ansible as well :thinking: 

But that means we miss out on openssl security patches

**Review by fisherking — APPROVED** [review]

**Review by mhalmagiu — APPROVED** [review]

**Comment by sjagoe** [comment]
How do we build & release heaven?

**Review by tstm — APPROVED** [review]

**Comment by sjagoe** [comment]
We can't do this yet; we need to set up a rust compiler in the container as well.

**Comment by sjagoe** [comment]
Sorry, I'm going back and forth here :/ I can't convince myself which is a better approach. 

I don't like pinning cryptography in smartly-ansible because that means no openssl security fixes everywhere for all devops. I've got this working now.

**Review by fisherking — APPROVED** [review]

**Pull request merged**
