### PR TITLE
Don't ping on successful deploy

### PR DESCRIPTION
**Pull request by juusom**
Because it's noisy and annoying

### CODE REVIEW

**Review by juhakuu — APPROVED** [review]
Looks fine to me.

**Review by mhalmagiu — COMMENTED** [review]
No idea how to deploy this, but I'm 100% good with the change.

**Comment by juusom** [comment]
@mhalmagiu, there's `heaven.yml` in the ansible repo. I already ran it.

**Comment by juusom** [comment]
Actually, there's a build script here: `bin/docker-production-build` which needs to be run first

**Pull request merged**
